// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMaR-gR4w10kmYTFxzk-np8-AAYXnNSA4',
    appId: '1:228236395928:web:6b72df2381d048c50b17ed',
    messagingSenderId: '228236395928',
    projectId: 'registration-7976b',
    authDomain: 'registration-7976b.firebaseapp.com',
    storageBucket: 'registration-7976b.firebasestorage.app',
    measurementId: 'G-8KJ7MC6D0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFVktSt93zJ-aDTl0cgUI9-_0kQVhUZHI',
    appId: '1:228236395928:android:1c3cc3ccd6536e570b17ed',
    messagingSenderId: '228236395928',
    projectId: 'registration-7976b',
    storageBucket: 'registration-7976b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB08FtrcnUL-3Se-aHJay4HXB0tebv60Jw',
    appId: '1:228236395928:ios:afc3baef5a2f20eb0b17ed',
    messagingSenderId: '228236395928',
    projectId: 'registration-7976b',
    storageBucket: 'registration-7976b.firebasestorage.app',
    iosBundleId: 'com.example.loginapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB08FtrcnUL-3Se-aHJay4HXB0tebv60Jw',
    appId: '1:228236395928:ios:afc3baef5a2f20eb0b17ed',
    messagingSenderId: '228236395928',
    projectId: 'registration-7976b',
    storageBucket: 'registration-7976b.firebasestorage.app',
    iosBundleId: 'com.example.loginapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMaR-gR4w10kmYTFxzk-np8-AAYXnNSA4',
    appId: '1:228236395928:web:6f677ee0290723f00b17ed',
    messagingSenderId: '228236395928',
    projectId: 'registration-7976b',
    authDomain: 'registration-7976b.firebaseapp.com',
    storageBucket: 'registration-7976b.firebasestorage.app',
    measurementId: 'G-V0M82XWPJH',
  );
}
